<a href="https://colab.research.google.com/github/yuldashevsamandar9-coder/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [8]:
import pandas as pd

In [10]:
print(pd.__version__)

2.2.3

In [16]:
mydataset = {
  'cars': ["BMW", "Volvo", "Ford","Tesla", "Ferrari", "Matiz"],
  'counts': [3, 7, 2,6,4,3]
}
print(mydataset)
print("-============")

df = pd.DataFrame(mydataset)

print(df)

{'cars': ['BMW', 'Volvo', 'Ford', 'Tesla', 'Ferrari', 'Matiz'], 'counts': [3, 7, 2, 6, 4, 3]}
-============
      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       6
4  Ferrari       4
5    Matiz       3

In [23]:
df.head() #boshiudan 5 ta maliumot uqib beradi

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       6
4  Ferrari       4

In [26]:
df.tail() # oxiridan 5 ta kursatib beradi

      cars  counts
1    Volvo       7
2     Ford       2
3    Tesla       6
4  Ferrari       4
5    Matiz       3

In [28]:
df.shape

(6, 2)

In [30]:
df.columns #typelarini kursatadi

Index(['cars', 'counts'], dtype='object')

In [31]:
df.dtypes # malumotlarning typeni aniqlaydi

cars      object
counts     int64
dtype: object

In [34]:
df.describe() # numerical columns only

         counts
count  6.000000
mean   4.166667
std    1.940790
min    2.000000
25%    3.000000
50%    3.500000
75%    5.500000
max    7.000000

In [37]:
df.iloc[1:5]

      cars  counts
1    Volvo       7
2     Ford       2
3    Tesla       6
4  Ferrari       4

In [42]:
df.loc[2, "cars"]

'Ford'

In [48]:
print (df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       6
4  Ferrari       4
5    Matiz       3

In [50]:
df[df["cars"]  =="Volvo"]

    cars  counts
1  Volvo       7

In [53]:
df.mean(numeric_only = True) # raqamlarning urtachasini aniqlab berarkan

counts    4.166667
dtype: float64

In [54]:
df.sum() # yigindisini chiqarib beradi

cars      BMWVolvoFordTeslaFerrariMatiz
counts                               25
dtype: object

In [55]:
df.min()

cars      BMW
counts      2
dtype: object

In [56]:
df.max()

cars      Volvo
counts        7
dtype: object

In [58]:
df.median(numeric_only=True) # midle valueni olib beradi

counts    3.5
dtype: float64

In [59]:
df.count() nan valuelarni qidiradi

cars      6
counts    6
dtype: int64

In [60]:
df.std(numeric_only=True)

counts    1.94079
dtype: float64

In [67]:
data_with_missing = {
    "cars:": ["BWM", "TESLA", None, "VOLVO"],
    "counst": [8, 9, None, 4]
}
df.missing = pd.DataFrame(data_with_missing)
print(df.missing)

   cars:  counst
0    BWM     8.0
1  TESLA     9.0
2   None     NaN
3  VOLVO     4.0

/tmp/ipykernel_548/1459979515.py:5: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.missing = pd.DataFrame(data_with_missing)

In [69]:
df.missing.isnull().sum() #datalrni tozalashda ishlatiladi sum data bor yuglini aniqlaydi

cars:     1
counst    1
dtype: int64

In [72]:
df.missing.dropna() # mauloti yugni uchirvoradi

   cars:  counst
0    BWM     8.0
1  TESLA     9.0
3  VOLVO     4.0

In [73]:
df.missing.dropna(how="all") # mauloti bittasi bulsa uchirmaydi

   cars:  counst
0    BWM     8.0
1  TESLA     9.0
3  VOLVO     4.0

In [74]:
df.missing.dropna(axis=1) #bitta ham malumot bulmasa hammasini uchirvoradi columnda turganlarni

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [77]:
df.missing.dropna(subset=['counst']) # countsni tekshirib malumot bor yuglini aniqlaydi

   cars:  counst
0    BWM     8.0
1  TESLA     9.0
3  VOLVO     4.0

In [79]:
df.missing.fillna(0) # malumoti yug qatorga malumot quyib quyadi

   cars:  counst
0    BWM     8.0
1  TESLA     9.0
2      0     0.0
3  VOLVO     4.0

In [81]:
df.missing.fillna('unkwon') # malumoti yug qatorga malumot quyib quyadi

    cars:  counst
0     BWM     8.0
1   TESLA     9.0
2  unkwon  unkwon
3   VOLVO     4.0

In [86]:
df.missing.fillna({'cars:': 'unkwon', 'counst': 0}) # malumoti yug qatorga malumot quyib quyadi

    cars:  counst
0     BWM     8.0
1   TESLA     9.0
2  unkwon     0.0
3   VOLVO     4.0

In [103]:
df = pd.read_csv("Titanic-Dataset.csv")
df.tail(30)
# df= pd.read_excel("Titanic-Dataset.excel")
df.fillna({"Cabin": "HELLO WORLD"})

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,HELLO WORLD,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,HELLO WORLD,S
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,HELLO WORLD,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,HELLO WORLD,S
887,887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,HELLO WORLD,S
889,889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,HELLO WORLD,Q

In [98]:
df.to_csv("Titanic-Dataset.csv")

In [94]:
# serias => 1D
cars = pd.Series(["BWM", "TESLA", "PORSHE"])
print(cars)

0       BWM
1     TESLA
2    PORSHE
dtype: object